# github: [andrea-mariadb-2, andrea_mariadb, andipandi111, 777ninjamusic]
patreon: andrea_mariadb
open_collective: andrea_mariadb
ko_fi: andrea_mariadb
tidelift: npm-andrea_mariadb
community_bridge: 
liberapay: andrea_mariadb
issuehunt: andrea-mariadb-2
otechie: andrea-mariadb
custom: ['https://www.youtube.com/channel/UCzTBP3CKnn_Pfn9x1ESaOZA', 'https://www.youtube.com/channel/UCC28NtoyhL4o_tg3r1cmicA', 'https://www.youtube.com/channel/UCeTsecOxtD8zuDKPpcL9crg', 'https://www.youtube.com/channel/UCuoDzKdqTwXtJe5kwo4tNYQ']
.yml
.yaml
.npm

